apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      containers:
        - name: frontend
          image: "{{ .Values.acrLoginServer }}/frontend:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef: { name: environment-config }
            - configMapRef: { name: service-api-config }
          env:
            - { name: PORT, value: "8080" }
            - { name: ENABLE_TRACING, value: "false" }
            - { name: ENABLE_METRICS, value: "false" }
            - { name: SCHEME, value: "http" }
            - { name: LOG_LEVEL, value: "info" }
            - { name: DEFAULT_USERNAME, value: "testuser" }
            - { name: DEFAULT_PASSWORD, value: "password" }
            - { name: BANK_NAME, value: "Bank of Anthos" }
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keys
              mountPath: /root/.ssh
              readOnly: true
            # - { name: publickey, mountPath: /root/.ssh, readOnly: true }
      volumes:
          - name: keys
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: jwt-key-provider
        # - name: publickey
        #   secret:
        #     secretName: jwt-key
        #     items:
        #       - { key: jwtRS256.key.pub, path: publickey }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080