apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jwt-key-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.csiClientId }}
    keyvaultName: {{ .Values.keyvaultName }}
    tenantId: {{ .Values.tenantId }}
    objects: |
      array:
        - |
          objectName: jwt-private-key
          objectType: secret
          objectAlias: privatekey
        - |
          objectName: jwt-public-key
          objectType: secret
          objectAlias: publickey
        - |
          objectName: postgres-admin-password
          objectType: secret
          objectAlias: pgpassword
  secretObjects:
    - secretName: boa-db-credentials
      type: Opaque
      data:
        - objectName: pgpassword
          key: password

# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: jwt-key-provider
#   # annotations:
#   #   "helm.sh/hook": pre-install,pre-upgrade
#   #   "helm.sh/hook-weight": "-10"
#   #   "helm.sh/hook-delete-policy": before-hook-creation
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "true"
#     userAssignedIdentityID: {{ .Values.csiClientId }}
#     keyvaultName: {{ .Values.keyvaultName }}
#     tenantId: {{ .Values.tenantId }}
#     objects: |
#       array:
#         - |
#           objectName: jwt-private-key
#           objectType: secret
#           objectAlias: privatekey
#         - |
#           objectName: jwt-public-key
#           objectType: secret
#           objectAlias: publickey
#   # secretObjects:
#   #   - secretName: jwt-key
#   #     type: Opaque
#   #     data:
#   #       - objectName: jwt-private-key
#   #         key: jwtRS256.key
#   #       - objectName: jwt-public-key
#   #         key: jwtRS256.key.pub